### ISSUE TITLE
'algorithm' file not found in case of iOS

### ISSUE THREAD

**Issue by anupsamanta** [payu-intrepos/payu-non-seamless-react#68]
### After upgrading **"payu-non-seam-less-react"** to version 3.1.2 I am getting error **'algorithm' file not found** in case of iOS. In android it is working fine.  Note for iOS I am using Xcode version 15.0. Any help would be highly appreciated.

**Comment by anupsamanta** [comment]
Fixed now.

**Comment by sharvanappinventiv** [comment]
This error is still existing with `"payu-non-seam-less-react": "^3.1.3-alpha1",` in **### iOS** `'algorithm' file not found`, in android working fine
